version: '3.7'
services:

 postgres:
  image: postgres:11.1-alpine
  container_name: postgres
  env_file: 
   - ./variables.env
   - ~/.metabase_secrets.env
  expose:
   - "5432"
  volumes:
   - "pgdata:/var/lib/postgresql/data"

 metabase:
  image: metabase/metabase:latest
  container_name: metabase
  depends_on:
   - postgres
  env_file: 
   - ./variables.env
   - ~/.metabase_secrets.env
  ports:
   - "3000:3000"
    
volumes:
 pgdata:
